services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln_db
      MYSQL_USER: vuln
      MYSQL_PASSWORD: vuln
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  php:
    build: ./site/php     
    ports:
      - "8081:80"
    volumes:
      - ./site/php:/var/www/html
    depends_on:
      - mysql

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: vuln_db
      POSTGRES_USER: vuln
      POSTGRES_PASSWORD: vuln
    ports:
      - "5433:5432"
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d

  flask:
    build: ./site/flask
    container_name: flask
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      POSTGRES_USER: vuln
      POSTGRES_PASSWORD: vuln
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: vuln_db
    volumes:
      - ./site/flask:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres